### ISSUE TITLE
Add-On: Brush Items

### ISSUE THREAD

**Issue by RainbowDashLabs** [eldoriarpg/SchematicBrushReborn#111]
Implement an add/on which:

- Allows to bind schematics on any item which can be a world edit brush -> SchematicTool
  - Every tool has an unique id, which will be saved as nbt tag. Allowing renaming of the tool without loosing the connection and not depending on any user input.
  - The tag points to a schematic, which was copied with the id into an own plugin internal directory in order to prevent modification of the schematic by accident
  - A brush can require a permission as well, which is saved in the brush config
  - If a player swaps the SchematicTool in their hand a schematic brush will be created holding the defined schematic
- It should be possible to check the current applied brush on an item to see its id.
- It should be possible to get a list of all existing SchematicTool ids and their schematics
- Schematic tools can be invalidated by invaliding the id, which will render all SchematicTools with this id unusable
- The tools should have a configurable usage limit.
- The preview needs to be enabled for those users automatically. Enabling the preview for those users should be configurable.
- No protection hooks required since this will already taken care of by world edit protections hooks
- Questionable: Adding a world edit flag to define if a SchematicTool can be used in this region.

This request was initially done by @TomLewis in #87 and is orientated on the implementation of [structure boxes](https://dev.bukkit.org/projects/structure-boxes)

**Comment by TomLewis** [comment]
Though of another use case, this is basically binding one of you're presets to specifically named items? Sorry I've not used your presets yet. Bought the plugin yesterday!

Because then you could have a kit on creative with a set of pre made building tools, like you could have a foliage kit, a brush with trees, a brush with bushes, a brushs etc under /kit foliage, then you have a few staff members able to create new items, which they can then put in kits, and then you have a whole set of tools an entire playerbase can use without having to learn a plugin!

The ease of a big standard player using a kit, being given items that they just need to point and click! Bloody brilliant! 

The more I think about it the more ideas I have!

**Comment by RainbowDashLabs** [comment]
I think the most easy aproach would be to wait for the implementation of saving complete brushes and just bind these on items.

That the next step on the roadmap after rewriting the preset saving.

**Comment by RainbowDashLabs** [comment]
@TomLewis A first implementation is done. It came out a bit different, but I think its a good solution as well:
https://eldonexus.de/repository/maven-dev/de/eldoria/schematic-tools/1.0.0-DEV/schematic-tools-1.0.0-DEV-all.jar

I also created a wiki page to document the basic setup and usage. Would love to get some feedback!
https://github.com/eldoriarpg/schematic-tools/wiki

**Comment by RainbowDashLabs** [comment]
Implemented and released
https://www.spigotmc.org/resources/schematic-tools-schematic-brush-reborn-2-0-add-on.103776/

**Comment by TomLewis** [comment]
Woohoo! fantastic work! I will see if I can test it soon! Thank you, this will be absolutely amazing addition!
